module.exports = {
    APP_ID: 'APP ID',
    APP_SECRET: 'APP SECRET',
    APP_URL: 'APP URL',
    YELP_KEY: "UqXizzKMtmdC-2rj32YE7Q",
  YELP_SECRET: "MdDNtIsK029Yccbtp-_f9cRfGL4",
  YELP_TOKEN: "UCAyWQm60Axw8TNYQvXhX9r8YNfc51Lo",
  YELP_TOKEN_SECRET: "GCIfYIjMX4FQxM7CP7BAAuVCbsU"
};